export const uid=()=>globalThis.crypto.randomUUID();
export const emptyState=()=>({profile:null,plan:null,meals:[],workouts:[],weights:[]});
export const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export function weekDays(date){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()-((d.getDay()+6)%7));return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(x.getDate()+i);return localDate(x)});}
export const number=(v)=>{const n=Number(String(v).replace(',','.'));if(!Number.isFinite(n)||n<0)throw Error('Use um número válido, igual ou maior que zero.');return n;};
export const totals=items=>items.reduce((a,x)=>{for(const k of ['calories','protein','carbs','fat'])a[k]+=(x[k]===null?0:number(x[k]??0));return a},{calories:0,protein:0,carbs:0,fat:0});
export function scaleItem(item,quantity){quantity=number(quantity);if(!(item.quantity>0))throw Error('A quantidade de referência deve ser maior que zero.');return {...item,quantity,...Object.fromEntries(['calories','protein','carbs','fat'].map(k=>[k,item[k]===null?null:Math.round(number(item[k]??0)*quantity/item.quantity*10)/10]))};}
export function validateMeal(m){if(!/^\d{4}-\d{2}-\d{2}$/.test(m.date)||!m.items?.length||m.items.length>30)throw Error('Confira a data e os alimentos.');m.items.forEach(i=>{if(!i.name?.trim()||!(number(i.quantity)>0)||!['g','ml','porção'].includes(i.unit)||i.calories===null)throw Error('Preencha nome, quantidade, unidade e calorias de cada alimento.');for(const k of ['calories','protein','carbs','fat'])if(i[k]!==null)number(i[k]);});return m;}
export const equipmentOptions={machine:'Máquinas da academia',cable:'Polia / cabos',dumbbell:'Halteres e banco',body:'Peso corporal',bike:'Bicicleta',treadmill:'Passadeira / esteira'};
// Guias gerais de execução. Carga é sempre registada pelo utilizador, nunca prescrita pelo peso corporal.
const ex=(id,name,group,equipment,device,steps,mistakes)=>({id,name,group,equipment,device,steps,mistakes});
export const exercises=[
ex('chest','Chest press','upper','machine','Máquina de supino sentado',['Ajuste o banco para que as pegas fiquem próximas da linha do peito.','Mantenha pés apoiados e costas no encosto. Empurre sem bloquear os cotovelos.','Volte devagar, dentro de uma amplitude confortável. Expire ao empurrar.'],'Evite levantar os ombros ou afastar as costas do encosto.'),
ex('dbpress','Supino com halteres','upper','dumbbell','Banco plano e dois halteres',['Deite no banco com pés firmes no chão e halteres junto ao peito.','Empurre os halteres, mantendo punhos alinhados e ombros estáveis.','Desça com controlo, sem forçar a amplitude dos ombros.'],'Evite bater os halteres ou arquear excessivamente as costas.'),
ex('row','Remada sentada','upper','machine','Máquina de remada com apoio',['Ajuste o banco e apoie o tronco, se houver encosto frontal.','Puxe as pegas em direção ao tronco, com cotovelos próximos do corpo.','Volte devagar, sem arredondar ou balançar as costas.'],'Não puxe com o impulso do tronco.'),
ex('cablerow','Remada na polia','upper','cable','Polia baixa com pega neutra',['Sente com pés apoiados e coluna confortável.','Puxe a pega em direção à cintura, sem inclinar o tronco para trás.','Estenda os braços devagar e mantenha os ombros controlados.'],'Evite balançar o tronco para mover a carga.'),
ex('dbrow','Remada unilateral','upper','dumbbell','Halter e banco',['Apoie uma mão e um joelho no banco. Mantenha costas alinhadas.','Puxe o halter em direção à anca sem rodar o tronco.','Desça devagar. Faça as repetições de ambos os lados.'],'Evite rodar o tronco ou encolher o ombro.'),
ex('pulldown','Puxada à frente','upper','cable','Polia alta com barra',['Regule o apoio das coxas e segure a barra numa largura confortável.','Puxe a barra à frente em direção ao alto do peito.','Volte devagar, evitando inclinar muito o tronco.'],'Não puxe a barra atrás da nuca.'),
ex('shoulder','Shoulder press','upper','machine','Máquina de desenvolvimento',['Ajuste o banco para iniciar com as pegas na altura dos ombros.','Com costas apoiadas, empurre para cima sem bloquear os cotovelos.','Volte devagar até uma posição confortável.'],'Não force amplitude dolorosa nem arqueie as costas.'),
ex('dbshoulder','Desenvolvimento sentado','upper','dumbbell','Banco com encosto e halteres',['Sente com costas apoiadas, pés firmes e halteres junto aos ombros.','Empurre para cima com punhos alinhados aos antebraços.','Desça com controlo e mantenha as costas apoiadas.'],'Evite compensar a carga com a região lombar.'),
ex('lateral','Elevação lateral','upper','dumbbell','Dois halteres leves',['Fique com pés estáveis e cotovelos ligeiramente fletidos.','Eleve os braços de forma controlada até uma altura confortável, próxima dos ombros.','Desça devagar, sem embalar o corpo.'],'Não balance o tronco nem encolha os ombros.'),
ex('curl','Rosca martelo','upper','dumbbell','Dois halteres',['Mantenha as palmas voltadas uma para a outra e cotovelos junto ao tronco.','Dobre os cotovelos sem mover os braços para a frente.','Desça os halteres de forma controlada.'],'Evite usar impulso das costas.'),
ex('triceps','Tríceps na polia','upper','cable','Polia alta e corda',['Segure a corda com cotovelos junto ao tronco.','Estenda os cotovelos para baixo, sem deslocar os ombros.','Regresse devagar à posição inicial.'],'Não use o peso do corpo para empurrar a corda.'),
ex('pushup','Flexão inclinada','upper','body','Apoio elevado, firme e estável',['Apoie as mãos numa superfície fixa na altura adequada.','Mantenha corpo alinhado e dobre os cotovelos numa amplitude confortável.','Empurre para voltar. Um apoio mais alto reduz a dificuldade.'],'Não use uma cadeira solta ou superfície que escorregue.'),
ex('legpress','Leg press','lower','machine','Máquina de prensa de pernas',['Peça ajuda para ajustar banco e travas antes de começar.','Mantenha pés apoiados e joelhos a acompanhar a direção dos pés.','Desça só enquanto a bacia fica apoiada. Empurre sem bloquear os joelhos.'],'Evite descer até a lombar sair do encosto.'),
ex('squat','Agachamento até ao banco','lower','body','Banco firme e estável',['Posicione um banco atrás e mantenha os pés numa posição confortável.','Leve a anca para trás, dobre joelhos e toque suavemente no banco.','Levante com controlo e joelhos alinhados aos pés.'],'Não se deixe cair no banco nem force uma amplitude dolorosa.'),
ex('goblet','Agachamento goblet','lower','dumbbell','Halter e banco como referência',['Segure um halter junto ao peito e mantenha pés estáveis.','Agache lentamente até uma amplitude confortável.','Suba mantendo o tronco controlado e os joelhos alinhados aos pés.'],'Evite perder o apoio do pé ou arredondar as costas.'),
ex('legcurl','Flexão de pernas','lower','machine','Máquina de flexora',['Alinhe o eixo da máquina com o joelho e ajuste os apoios.','Dobre os joelhos sem levantar a bacia ou arquear a lombar.','Volte devagar, mantendo o controlo da carga.'],'Evite elevar a anca ou acelerar o regresso.'),
ex('extension','Extensão de pernas','lower','machine','Máquina de extensora',['Ajuste o banco com o eixo alinhado ao joelho e apoio acima do tornozelo.','Estenda as pernas de forma controlada, sem bloquear os joelhos.','Desça devagar. Use apenas uma amplitude confortável.'],'Pare se surgir dor no joelho.'),
ex('rdl','Peso morto romeno com halteres','lower','dumbbell','Dois halteres',['Comece com halteres junto às coxas e joelhos ligeiramente fletidos.','Leve a anca para trás, com halteres próximos das pernas e costas estáveis.','Volte estendendo a anca, sem inclinar as costas para trás.'],'Use uma carga leve para aprender o movimento com um instrutor.'),
ex('bridge','Ponte de glúteos','lower','body','Colchonete',['Deite de costas, joelhos fletidos e pés apoiados.','Eleve a anca de forma controlada sem arquear a lombar.','Volte devagar. Ajuste a amplitude para ficar confortável.'],'Evite elevar a anca à custa de arquear as costas.'),
ex('calf','Elevação de gémeos','lower','body','Apoio fixo para equilíbrio',['Fique de pé segurando num apoio fixo.','Suba os calcanhares devagar mantendo os tornozelos estáveis.','Desça com controlo. Pode começar sentado se necessário.'],'Não salte nem balance o corpo.'),
ex('deadbug','Dead bug','core','body','Colchonete',['Deite de costas com braços para cima e joelhos fletidos.','Estenda lentamente um braço e a perna oposta sem perder controlo do tronco.','Volte e alterne os lados. Reduza a amplitude se necessário.'],'Evite arquear a lombar; cada lado conta como uma repetição.'),
ex('bird','Bird dog','core','body','Colchonete',['Apoie mãos e joelhos, numa posição confortável.','Estenda um braço e a perna oposta sem rodar a bacia.','Volte lentamente e alterne os lados.'],'Não arqueie as costas nem procure altura excessiva.'),
];
export function generatePlan(p){if(!p||!p.screened)throw Error('Preencha o perfil e a confirmação de restrições primeiro.');if(p.restriction?.trim())throw Error('Há uma restrição indicada. Peça orientação ao profissional antes de gerar o plano; não a apague sem a resolver.');if(!Array.isArray(p.equipment)||!p.equipment.length)throw Error('Escolha os equipamentos disponíveis.');
const pick=ids=>ids.map(id=>exercises.find(e=>e.id===id)).find(e=>p.equipment.includes(e.equipment)&&!(p.exclude||[]).includes(e.group));
const upper=[['chest','dbpress','pushup'],['row','cablerow','dbrow'],['pulldown','dbrow','row'],['shoulder','dbshoulder','pushup'],['lateral','curl','triceps']];
const lower=[['legpress','goblet','squat'],['legcurl','rdl','bridge'],['extension','squat','goblet'],['bridge','rdl','legcurl'],['calf'],['deadbug','bird']];
const compact=Number(p.minutes)<=40;const sets=p.level==='beginner'?2:3;
let specs=[['A','Superiores A',upper],['B','Inferiores A',lower],['C','Superiores B',[upper[1],upper[0],upper[3],upper[2],['curl','triceps','lateral']]],['D','Inferiores B',[lower[1],lower[0],lower[3],lower[4],['bird','deadbug']]]];
return {id:'plan',createdAt:new Date().toISOString(),sessions:specs.map(([id,name,groups])=>{const seen=new Set();const selected=groups.map(pick).filter(e=>e&&!seen.has(e.id)&&seen.add(e.id)).slice(0,compact?4:6);return {id,name,exercises:selected.map(e=>({...e,sets,reps:e.group==='core'?'6–10 por lado':'8–12',rest:e.group==='core'?60:90})),cardio:p.equipment.includes('bike')?'Bicicleta':p.equipment.includes('treadmill')?'Caminhada na passadeira':null,cardioMinutes:compact?10:15};}),schedule:'Segunda A · terça B · quinta C · sexta D. Pode ajustar os dias, mantendo recuperação entre sessões do mesmo grupo.',progression:'Comece com uma carga que permita terminar as séries com técnica estável e cerca de 2–3 repetições em reserva. Ao atingir o topo das repetições em todas as séries sem dor e com boa técnica em duas sessões, aumente o menor incremento disponível.',note:'Plano inicial por regras, ajustado aos equipamentos e ao tempo. Não utiliza IA para prescrever cargas nem trata lesões.'};}
export function validateState(s){
 if(!s||!['meals','workouts','weights'].every(k=>Array.isArray(s[k])&&s[k].length<=10000))throw Error('Backup inválido.');
 const ids=new Set(['profile','plan']);
 const validDate=d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&localDate(new Date(d+'T12:00:00'))===d;
 const text=(v,max=1000)=>typeof v==='string'&&v.length<=max;
 s.meals.forEach(m=>{validateMeal(m);if(!validDate(m.date)||!text(m.type,40)||!text(m.time,5)||!['manual','plate','label'].includes(m.source))throw Error('Refeição inválida no backup.');});
 for(const k of ['meals','workouts','weights'])for(const x of s[k]){if(!text(x.id,100)||!x.id||ids.has(x.id)||!validDate(x.date))throw Error('Backup com registos duplicados ou inválidos.');ids.add(x.id);}
 for(const w of s.weights)if(!(number(w.value)>=35&&number(w.value)<=350))throw Error('Peso inválido no backup.');
 for(const w of s.workouts){if(!text(w.name,100)||!Array.isArray(w.entries)||w.entries.length>30||!(number(w.minutes)>0&&number(w.minutes)<=240))throw Error('Treino inválido no backup.');for(const e of w.entries){if(!text(e.name,100))throw Error('Exercício inválido.');for(const k of ['kg','reps','sets'])if(e[k]!==null&&e[k]!==undefined)number(e[k]);}}
 if(s.profile){const p=s.profile;if(!text(p.name,60)||!text(p.restriction||'')||!Array.isArray(p.equipment)||p.equipment.some(x=>!Object.hasOwn(equipmentOptions,x))||!Array.isArray(p.exclude)||p.exclude.some(x=>!['upper','lower','core'].includes(x)))throw Error('Perfil inválido no backup.');for(const k of ['age','height','weight','minutes'])if(!Number.isFinite(Number(p[k]))||Number(p[k])<=0)throw Error('Dados de perfil inválidos.');}
 // Reconstituir a partir do catálogo seguro evita aceitar HTML ou instruções num plano importado.
 if(s.plan)s.plan=generatePlan(s.profile);
 return s;
}
export function stateRecords(s){return [...(s.profile?[{id:'profile',kind:'profile',data:s.profile}]:[]),...(s.plan?[{id:'plan',kind:'plan',data:s.plan}]:[]),...['meals','workouts','weights'].flatMap(kind=>s[kind].map(data=>({id:data.id,kind,data})))];}
export function applyRecord(s,r){if(r.kind==='profile'||r.kind==='plan')s[r.kind]=r.deleted?null:r.data;else if(['meals','workouts','weights'].includes(r.kind)){s[r.kind]=s[r.kind].filter(x=>x.id!==r.id);if(!r.deleted)s[r.kind].push(r.data);}return s;}
