import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function server({auth=true,quota=true,output=null}={}){let handler;const calls=[];const env={ALLOWED_ORIGIN:'https://rafaelgiacometti-beep.github.io',SUPABASE_URL:'https://fake.supabase.co',SUPABASE_ANON_KEY:'public',OPENAI_API_KEY:'TEST_ONLY_NOT_A_REAL_KEY'};const fetch=async(url,opts)=>{calls.push(url);if(url.endsWith('/auth/v1/user'))return new Response(JSON.stringify(auth?{id:'user'}:{}),{status:auth?200:401});if(url.endsWith('/rpc/rgfit_claim_ai'))return new Response(JSON.stringify(quota?1:{message:'Quota bloqueada'}),{status:quota?200:403});return new Response(JSON.stringify({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(output)}]}]}),{status:200});};
let code=fs.readFileSync(new URL('../supabase/functions/rgfit-analyze/index.ts',import.meta.url),'utf8');for(const [from,to]of [['req:Request','req'],['body:unknown','body'],['const chunks:Uint8Array[]','const chunks'],['(x:any)','(x)'],['(i:any)','(i)']])code=code.replaceAll(from,to);vm.runInNewContext(code,{Deno:{env:{get:k=>env[k]},serve:f=>handler=f},fetch,Response,Request,AbortSignal,Uint8Array,TextDecoder,JSON,Number,Object,Array,Error});return {handler,calls};}
const request=(body={},headers={})=>new Request('https://fake.supabase.co/functions/v1/rgfit-analyze',{method:'POST',headers:{origin:'https://rafaelgiacometti-beep.github.io',authorization:'Bearer test-user',...headers},body:JSON.stringify(body)});
const payload={mode:'plate',image:'data:image/jpeg;base64,YWJj',context:'Frango'};
const item={name:'Frango',quantity:100,unit:'g',calories:165,protein:31,carbs:0,fat:4};
test('servidor bloqueia origem e token inválidos antes da IA',async()=>{const s=server();assert.equal((await s.handler(request(payload,{origin:'https://evil.example'}))).status,403);assert.equal(s.calls.length,0);const a=server({auth:false});assert.equal((await a.handler(request(payload))).status,401);assert.ok(!a.calls.some(x=>x.includes('openai')))});
test('quota e pedido inválido não consomem API da IA',async()=>{const q=server({quota:false});assert.equal((await q.handler(request(payload))).status,429);assert.ok(!q.calls.some(x=>x.includes('openai')));const s=server();assert.equal((await s.handler(request({...payload,image:'https://untrusted.example'}))).status,400);assert.equal(s.calls.length,1)});
test('resposta estruturada válida chega ao cliente',async()=>{const s=server({output:{readable:true,explanation:'',notes:'Estimativa',items:[item]}});const r=await s.handler(request(payload));assert.equal(r.status,200);assert.equal((await r.json()).items[0].calories,165);assert.equal(s.calls.length,3)});
test('resposta sem calorias ou com rótulo ambíguo é rejeitada',async()=>{const s=server({output:{readable:true,explanation:'',notes:'',items:[{...item,calories:null}]}});assert.equal((await s.handler(request(payload))).status,422);const label=server({output:{readable:true,explanation:'',notes:'',items:[item,item]}});assert.equal((await label.handler(request({...payload,mode:'label'}))).status,422)});
test('imagem ilegível pode voltar sem valores inventados',async()=>{const s=server({output:{readable:false,explanation:'Foto ilegível',notes:'',items:[]}});const r=await s.handler(request(payload));assert.equal(r.status,200);assert.equal((await r.json()).readable,false)});
